version: '3.8'
services:
  
  postgres:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feed_db
    volumes: 
      - db:/var/lib/postgresql/data 
    
  rest-api:
    container_name: feed-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/feed_db
      
volumes:
  db:
    driver: local